class MadhyaPradeshVsDistrictsRepo {
    static getExpectedMadhyaPradeshDistricts() {
      return [
        { english: "Agar-Malwa", hindi: "आगर-मालवा", tamil: "அகர்-மால்வா", telugu: "అగర్-మాల్వా", marathi: "आगर-माळवा" },
        { english: "Alirajpur", hindi: "अलीराजपुर", tamil: "அலிராஜ்பூர்", telugu: "అలీరాజ్‌పూర్", marathi: "अलीराजपूर" },
        { english: "Anuppur", hindi: "अनूपपुर", tamil: "அனுப்பூர்", telugu: "అనుప్పూర్", marathi: "अनुपपूर" },
        { english: "Ashoknagar", hindi: "अशोकनगर", tamil: "அசோக்நகர்", telugu: "అశోక్‌నగర్", marathi: "अशोकनगर" },
        { english: "Balaghat", hindi: "बालाघाट", tamil: "பாலகாட்", telugu: "బాలాఘాట్", marathi: "बालाघाट" },
        { english: "Barwani", hindi: "बड़वानी", tamil: "பர்வானி", telugu: "బర్వానీ", marathi: "बरवणी" },
        { english: "Betul", hindi: "बैतूल", tamil: "பெதுல்", telugu: "బెతుల్", marathi: "बैतूल" },
        { english: "Bhind", hindi: "भिंड", tamil: "பிந்த்", telugu: "భింద్", marathi: "भिंड" },
        { english: "Bhopal", hindi: "भोपाल", tamil: "போபால்", telugu: "భోపాల్", marathi: "भोपाळ" },
        { english: "Burhanpur", hindi: "बुरहानपुर", tamil: "புர்ஹான்பூர்", telugu: "బుర్హాన్‌పూర్", marathi: "बुरहानपूर" },
        { english: "Chhatarpur", hindi: "छतरपुर", tamil: "சத்தர்பூர்", telugu: "ఛతర్పూర్", marathi: "छतरपूर" },
        { english: "Chhindwara", hindi: "छिंदवाड़ा", tamil: "சிந்த்வாரா", telugu: "చింద్వారా", marathi: "छिंदवाडा" },
        { english: "Damoh", hindi: "दमोह", tamil: "டாமோஹ்", telugu: "దామోహ్", marathi: "दमोह" },
        { english: "Datia", hindi: "दतिया", tamil: "டாடியா", telugu: "డాటియా", marathi: "दतिया" },
        { english: "Dewas", hindi: "देवास", tamil: "தேவாஸ்", telugu: "దేవాస్", marathi: "देवास" },
        { english: "Dhar", hindi: "धार", tamil: "தார்", telugu: "ధర్", marathi: "धार" },
        { english: "Dindori", hindi: "डिंडोरी", tamil: "திண்டோரி", telugu: "దిండోరి", marathi: "दिंडोरी" },
        { english: "Guna", hindi: "गुना", tamil: "குணா", telugu: "గుణ", marathi: "गुण" },
        { english: "Gwalior", hindi: "ग्वालियर", tamil: "குவாலியர்", telugu: "గ్వాలియర్", marathi: "ग्वाल्हेर" },
        { english: "Harda", hindi: "हरदा", tamil: "ஹர்தா", telugu: "హర్దా", marathi: "हरडा" },
        { english: "Hoshangabad", hindi: "होशंगाबाद", tamil: "ஹோஷங்காபாத்", telugu: "హోషంగాబాద్", marathi: "होशंगाबाद" },
        { english: "Indore", hindi: "इंदौर", tamil: "இந்தூர்", telugu: "ఇండోర్", marathi: "इंदूर" },
        { english: "Jabalpur", hindi: "जबलपुर", tamil: "ஜபல்பூர்", telugu: "జబల్పూర్", marathi: "जबलपूर" },
        { english: "Jhabua", hindi: "झाबुआ", tamil: "ஜபுவா", telugu: "ఝబువా", marathi: "झाबुआ" },
        { english: "Katni", hindi: "कटनी", tamil: "கட்னி", telugu: "కట్ని", marathi: "कटनी" },
        { english: "Khandwa (East Nimar)", hindi: "खंडवा (पूर्वी निमाड़)", tamil: "காண்ட்வா (கிழக்கு நிமார்)", telugu: "ఖాండ్వా (తూర్పు నిమార్)", marathi: "खांडवा (पूर्व निमार)" },
        { english: "Khargone (West Nimar)", hindi: "खरगोन (पश्चिम निमाड़)", tamil: "கர்கோன் (மேற்கு நிமார்)", telugu: "ఖర్గోన్ (పశ్చిమ నిమార్)", marathi: "खरगोन (पश्चिम निमार)" },
        { english: "Maihar", hindi: "मैहर", tamil: "மைஹர்", telugu: "మైహర్", marathi: "मैहर" },
        { english: "Mandla", hindi: "मंडला", tamil: "மாண்ட்லா", telugu: "మండల", marathi: "मांडला" },
        { english: "Mandsaur", hindi: "मंदसौर", tamil: "மந்த்சூர்", telugu: "మందసౌర్", marathi: "मंदसौर" },
        { english: "Mauganj", hindi: "मऊगंज", tamil: "மௌகன்ஜ்", telugu: "మౌగంజ్", marathi: "मौगंज" },
        { english: "Morena", hindi: "मुरैना", tamil: "மொரேனா", telugu: "మోరెనా", marathi: "मोरेना" },
        { english: "Nagda", hindi: "नागदा", tamil: "நாக்டா", telugu: "నాగ్డా", marathi: "नागडा" },
        { english: "Narmadapuram", hindi: "नर्मदापुरम", tamil: "நர்மதாபுரம்", telugu: "నర్మదాపురం", marathi: "नर्मदापुरम" },
        { english: "Narsinghpur", hindi: "नरसिंहपुर", tamil: "நரசிங்பூர்", telugu: "నర్సింగపూర్", marathi: "नरसिंगपूर" },
      { english: "Neemuch", hindi: "नीमच", tamil: "வேம்பு", telugu: "వేప", marathi: "नीमच" },
      { english: "Niwari", hindi: "निवाड़ी", tamil: "நிவாரி", telugu: "నివారి", marathi: "निवारी" },
      { english: "Pandhurna", hindi: "पांढुर्णा", tamil: "பாண்டுர்ணா", telugu: "పంధుర్ణ", marathi: "पांढुर्णा" },
      { english: "Panna", hindi: "पन्ना", tamil: "பண்ணா", telugu: "పన్నా", marathi: "पन्ना" },
      { english: "Raisen", hindi: "रायसेन", tamil: "உயர்த்தப்பட்டது", telugu: "రైసెన్", marathi: "रायसेन" },
      { english: "Rajgarh", hindi: "राजगढ़", tamil: "ராஜ்கர்", telugu: "రాజ్‌గఢ్", marathi: "राजगड" },
      { english: "Ratlam", hindi: "रतलाम", tamil: "ரத்லம்", telugu: "రత్లాం", marathi: "रतलाम" },
      { english: "Rewa", hindi: "रीवा", tamil: "ரேவா", telugu: "రేవా", marathi: "रेवा" },
      { english: "Sagar", hindi: "सागर", tamil: "சாகர்", telugu: "సాగర్", marathi: "सागर" },
      { english: "Satna", hindi: "सतना", tamil: "சத்னா", telugu: "సత్నా", marathi: "सतना" },
      { english: "Sehore", hindi: "सीहोर", tamil: "செஹோர்", telugu: "సెహోర్", marathi: "सिहोर" },
      { english: "Seoni", hindi: "सिवनी", tamil: "சியோனி", telugu: "సియోని", marathi: "सिवनी" },
      { english: "Shahdol", hindi: "शहडोल", tamil: "ஷஹதோல்", telugu: "షాహదోల్", marathi: "शहाडोल" },
      { english: "Shajapur", hindi: "शाजापुर", tamil: "ஷாஜாபூர்", telugu: "షాజాపూర్", marathi: "शाजापूर" },
      { english: "Sheopur", hindi: "श्योपुर", tamil: "ஷியோபூர்", telugu: "షియోపూర్", marathi: "श्योपूर" },
      { english: "Shivpuri", hindi: "शिवपुरी", tamil: "சிவபுரி", telugu: "శివపురి", marathi: "शिवपुरी" },
      { english: "Shujalpur", hindi: "शुजालपुर", tamil: "ஷுஜல்பூர்", telugu: "షుజల్‌పూర్", marathi: "शुजालपूर" },
      { english: "Sidhi", hindi: "सीधी", tamil: "சித்தி", telugu: "సిద్ధి", marathi: "सिधी" },
      { english: "Singrauli", hindi: "सिंगरौली", tamil: "சிங்ராலி", telugu: "సింగ్రౌలి", marathi: "सिंगरौली" },
      { english: "Tikamgarh", hindi: "टीकमगढ़", tamil: "திகம்கர்", telugu: "తికమ్‌గర్", marathi: "टिकमगड" },
      { english: "Ujjain", hindi: "उज्जैन", tamil: "உஜ்ஜயினி", telugu: "ఉజ్జయిని", marathi: "उज्जैन" },
      { english: "Umaria", hindi: "उमरिया", tamil: "உமரியா", telugu: "ఉమారియా", marathi: "उमरिया" },
      { english: "Vidisha", hindi: "विदिशा", tamil: "விதிஷா", telugu: "విదిశ", marathi: "विदिशा" }
      ];
    }
  }
  
  export default MadhyaPradeshVsDistrictsRepo;
  