class RajasthanVsDistrictsRepo {
    static getExpectedRajasthanDistricts() {
      return [
        { english: "Ajmer", hindi: "अजमेर", tamil: "அஜ்மீர்", telugu: "అజ్మీర్", marathi: "अजमेर" },
        { english: "Alwar", hindi: "अलवर", tamil: "ஆழ்வார்", telugu: "అల్వార్", marathi: "अलवर" },
        { english: "Antroli", hindi: "आंतरोली", tamil: "அந்தரோலி", telugu: "అంటరోలి", marathi: "अंत्रोली" },
        { english: "Anupgarh", hindi: "अनूपगढ़", tamil: "அனுப்கர்", telugu: "అనుప్‌ఘర్", marathi: "अनुपगढ" },
        { english: "Balotra", hindi: "बालोतरा", tamil: "பலோத்ரா", telugu: "బలోత్రా", marathi: "बालोत्रा" },
        { english: "Banswara", hindi: "बांसवाड़ा", tamil: "பன்ஸ்வாரா", telugu: "బన్స్వారా", marathi: "बांसवाडा" },
        { english: "Baran", hindi: "बारां", tamil: "பரான்", telugu: "బరన్", marathi: "बरण" },
        { english: "Barmer", hindi: "बाड़मेर", tamil: "பார்மர்", telugu: "బార్మర్", marathi: "बारमेर" },
        { english: "Beawar", hindi: "ब्यावर", tamil: "பீவர்", telugu: "బేవార్", marathi: "बेवारस" },
        { english: "Bharatpur", hindi: "भरतपुर", tamil: "பரத்பூர்", telugu: "భరత్పూర్", marathi: "भरतपूर" },
        { english: "Bhilwara", hindi: "भीलवाड़ा", tamil: "பில்வாரா", telugu: "భిల్వారా", marathi: "भिलवाडा" },
        { english: "Bikaner", hindi: "बीकानेर", tamil: "பிகானேர்", telugu: "బికనీర్", marathi: "बिकानेर" },
        { english: "Bundi", hindi: "बूंदी", tamil: "பூந்தி", telugu: "బండి", marathi: "बुंदी" },
        { english: "Chittorgarh", hindi: "चित्तौड़गढ़", tamil: "சித்தூர்கர்", telugu: "చిత్తోర్‌గఢ్", marathi: "चित्तोडगड" },
        { english: "Churu", hindi: "चुरू", tamil: "சுரு", telugu: "చురు", marathi: "चुरू" },
        { english: "Dausa", hindi: "दौसा", tamil: "தௌசா", telugu: "దౌసా", marathi: "दौसा" },
        { english: "Deeg", hindi: "डीग", tamil: "டீக்", telugu: "డీగ్", marathi: "डीग" },
        { english: "Dholpur", hindi: "धौलपुर", tamil: "தோல்பூர்", telugu: "ధోల్పూర్", marathi: "ढोलपूर" },
        { english: "Didwana-Kuchaman", hindi: "डीडवाना-कुचामन", tamil: "தித்வானா-குச்சமன்", telugu: "దిద్వానా-కూచమన్", marathi: "दिडवाना-कुचमन" },
        { english: "Dudu", hindi: "दूदू", tamil: "டுடு", telugu: "డూడూ", marathi: "दुडू" },
        { english: "Dungarpur", hindi: "डूंगरपुर", tamil: "துங்கர்பூர்", telugu: "దుంగార్పూర్", marathi: "डुंगरपूर" },
        { english: "Ganganagar", hindi: "गंगानगर", tamil: "கங்காநகர்", telugu: "గంగానగర్", marathi: "गंगानगर" },
        { english: "Gangapurcity", hindi: "गंगापुरसिटी", tamil: "கங்காபூர்சிட்டி", telugu: "గంగాపూర్సిటీ", marathi: "गंगापूरसिटी" },
        { english: "Hanumangarh", hindi: "हनुमानगढ़", tamil: "ஹனுமன்கர்", telugu: "హనుమాన్‌ఘర్", marathi: "हनुमानगड" },
        { english: "Jaipur", hindi: "जयपुर", tamil: "ஜெய்ப்பூர்", telugu: "జైపూర్", marathi: "जयपूर" },
        { english: "Jaipur (Gramin)", hindi: "जयपुर (ग्रामीण)", tamil: "ஜெய்ப்பூர் (கிராமின்)", telugu: "జైపూర్ (గ్రామిన్)", marathi: "जयपूर (ग्रामीण)" },
        { english: "Jaisalmer", hindi: "जैसलमेर", tamil: "ஜெய்சால்மர்", telugu: "జైసల్మేర్", marathi: "जैसलमेर" },
        { english: "Jalore", hindi: "जालोर", tamil: "ஜலோர்", telugu: "జాలోర్", marathi: "जालोरे" },
        { english: "Jhalawar", hindi: "झालावाड़", tamil: "ஜாலவார்", telugu: "ఝలావర్", marathi: "झालावार" },
        { english: "Jhunjhunu", hindi: "झुंझुनूं", tamil: "ஜுன்ஜுனு", telugu: "ఝుంఝును", marathi: "झुंझुनू" },
        { english: "Jodhpur", hindi: "जोधपुर", tamil: "ஜோத்பூர்", telugu: "జోధ్‌పూర్", marathi: "जोधपूर" },
        { english: "Jodhpur (Gramin)", hindi: "जोधपुर (ग्रामीण)", tamil: "ஜோத்பூர் (கிராமின்)", telugu: "జోధ్‌పూర్ (గ్రామీన్)", marathi: "जोधपूर (ग्रामीण)" },
        { english: "Karauli", hindi: "करौली", tamil: "கரௌலி", telugu: "కరౌలి", marathi: "करौली" },
        { english: "Kekri", hindi: "केकड़ी", tamil: "கெக்ரி", telugu: "కేక్రి", marathi: "केकरी" },
        { english: "Khairthal-Tijara", hindi: "खैरथल-तिजारा", tamil: "கைர்தல்-திஜாரா", telugu: "ఖైర్తాల్-తిజారా", marathi: "खैरथळ-तिजारा" },
        { english: "Kota", hindi: "कोटा", tamil: "கோட்டா", telugu: "కోట", marathi: "कोटा" },
        { english: "Kotputli-Behror", hindi: "कोटपूतली-बहरोड़", tamil: "கோட்புட்லி-பெஹ்ரோர்", telugu: "కోట్‌పుట్లీ-బెహ్రోర్", marathi: "कोटपुतली-बेहरोर" },
        { english: "Nagaur", hindi: "नागौर", tamil: "நாகௌர்", telugu: "నాగౌర్", marathi: "नागौर" },
        { english: "Neem Ka Thana", hindi: "नीम का थाना", tamil: "நீம் கா தானா", telugu: "నీమ్ క థానా", marathi: "कडुनिंब का ठाणे" },
        { english: "Pali", hindi: "पाली", tamil: "பாலி", telugu: "పాలి", marathi: "पाली" },
        { english: "Phalodi", hindi: "फलौदी", tamil: "பலோடி", telugu: "ఫలోడి", marathi: "फलोदी" },
        { english: "Pratapgarh", hindi: "प्रतापगढ़", tamil: "பிரதாப்கர்", telugu: "ప్రతాప్‌గఢ్", marathi: "प्रतापगड" },
        { english: "Rajsamand", hindi: "राजसमंद", tamil: "ராஜ்சமந்த்", telugu: "రాజసమంద్", marathi: "राजसमंद" },
        { english: "Salumbar", hindi: "सलूम्बर", tamil: "சாலும்பர்", telugu: "సాలుంబర్", marathi: "साळुंबर" },
        { english: "Sanchore", hindi: "सांचोर", tamil: "சாஞ்சோர்", telugu: "సంచోరే", marathi: "सांचोरे" },
        { english: "Sawai Madhopur", hindi: "सवाई माधोपुर", tamil: "சவாய் மாதோபூர்", telugu: "సవాయి మాధోపూర్", marathi: "सवाई माधोपूर" },
        { english: "Shahpura", hindi: "शाहपुरा", tamil: "ஷாபுரா", telugu: "షాహపురా", marathi: "शाहपुरा" },
        { english: "Sikar", hindi: "सीकर", tamil: "சிகார்", telugu: "సికర్", marathi: "सिकर" },
        { english: "Sirohi", hindi: "सिरोही", tamil: "சிரோஹி", telugu: "సిరోహి", marathi: "सिरोही" },
        { english: "Sriganganagar", hindi: "श्रीगंगानगर", tamil: "ஸ்ரீகங்கநகர்", telugu: "శ్రీగంగనగర్", marathi: "श्रीगंगानगर" },
        { english: "Tonk", hindi: "टोंक", tamil: "டோங்க்", telugu: "టోంక్", marathi: "टोंक" },
        { english: "Udaipur", hindi: "उदयपुर", tamil: "உதயபூர்", telugu: "ఉదయపూర్", marathi: "उदयपूर" }
      ];
    }
  }
  
  export default RajasthanVsDistrictsRepo;
  