class UttarPradeshVsDistrictsRepo {
    static getExpectedUttarPradeshDistricts() {
      return [
        { english: "Agra", hindi: "आगरा", tamil: "ஆக்ரா", telugu: "ఆగ్రా", marathi: "आग्रा" },
        { english: "Aligarh", hindi: "अलीगढ", tamil: "அலிகார்", telugu: "అలీఘర్", marathi: "अलीगढ" },
        { english: "Allahabad", hindi: "इलाहाबाद", tamil: "அலகாபாத்", telugu: "అలహాబాద్", marathi: "अलाहाबाद" },
        { english: "Ambedkar Nagar", hindi: "अंबेडकरनगर", tamil: "அம்பேத்கர் நகர்", telugu: "అంబేద్కర్ నగర్", marathi: "आंबेडकर नगर" },
        { english: "Amethi", hindi: "अमेठी", tamil: "அமேதி", telugu: "అమేథి", marathi: "अमेठी" },
        { english: "Amroha", hindi: "अमरोहा", tamil: "அம்ரோஹா", telugu: "అమ్రోహా", marathi: "अमरोहा" },
        { english: "Auraiya", hindi: "औरैया", tamil: "அவுரையா", telugu: "ఔరయ్యా", marathi: "औरैया" },
        { english: "Ayodhya", hindi: "अयोध्या", tamil: "அயோத்தி", telugu: "అయోధ్య", marathi: "अयोध्या" },
        { english: "Azamgarh", hindi: "आजमगढ़", tamil: "அசம்கர்", telugu: "అజంగఢ్", marathi: "आझमगड" },
        { english: "Badaun", hindi: "बदायूं", tamil: "படவுன்", telugu: "బదౌన్", marathi: "बदाऊन" },
        { english: "Baghpat", hindi: "बागपत", tamil: "பாக்பத்", telugu: "బాగ్పత్", marathi: "बागपत" },
        { english: "Bahraich", hindi: "बहराइच", tamil: "பஹ்ரைச்", telugu: "బహ్రైచ్", marathi: "बहराइच" },
        { english: "Ballia", hindi: "बलिया", tamil: "பல்லியா", telugu: "బల్లియా", marathi: "बलिया" },
        { english: "Balrampur", hindi: "बलरामपुर", tamil: "பல்ராம்பூர்", telugu: "బలరాంపూర్", marathi: "बलरामपूर" },
        { english: "Banda", hindi: "बांदा", tamil: "பண்டா", telugu: "బండ", marathi: "बांदा" },
        { english: "Bara Banki", hindi: "बाराबंकी", tamil: "பாரா பாங்கி", telugu: "బారా బాంకీ", marathi: "बारा बांकी" },
        { english: "Bareilly", hindi: "बरेली", tamil: "பரேலி", telugu: "బరేలీ", marathi: "बरेली" },
        { english: "Basti", hindi: "बस्ती", tamil: "பஸ்தி", telugu: "బస్తీ", marathi: "बस्ती" },
        { english: "Bhadohi", hindi: "भदोही", tamil: "பதோஹி", telugu: "భదోహి", marathi: "भदोही" },
        { english: "Bijnor", hindi: "बिजनौर", tamil: "பிஜ்னோர்", telugu: "బిజ్నోర్", marathi: "बिजनौर" },
        { english: "Budaun", hindi: "बदायूं", tamil: "புடான்", telugu: "బుదౌన్", marathi: "बुडाऊन" },
        { english: "Bulandshahr", hindi: "बुलंदशहर", tamil: "புலந்த்ஷாஹர்", telugu: "బులంద్‌షహర్", marathi: "बुलंदशहर" },
        { english: "Chandauli", hindi: "चंदौली", tamil: "சண்டௌலி", telugu: "చందౌలీ", marathi: "चांदौली" },
        { english: "Chitrakoot", hindi: "चित्रकूट", tamil: "சித்ரகூட்", telugu: "చిత్రకూట్", marathi: "चित्रकूट" },
        { english: "Deoria", hindi: "देवरिया", tamil: "டியோரியா", telugu: "డియోరియా", marathi: "देवरिया" },
        { english: "Etah", hindi: "एटा", tamil: "எட்டா", telugu: "ఎటాహ్", marathi: "एटा" },
        { english: "Etawah", hindi: "इटावा", tamil: "எட்டாவா", telugu: "ఇతావా", marathi: "इटावा" },
        { english: "Faizabad", hindi: "फैजाबाद", tamil: "பைசாபாத்", telugu: "ఫైజాబాద్", marathi: "फैजाबाद" },
        { english: "Farrukhabad", hindi: "फर्रुखाबाद", tamil: "ஃபரூக்காபாத்", telugu: "ఫరూఖాబాద్", marathi: "फारुखाबाद" },
        { english: "Fatehpur", hindi: "फतेहपुर", tamil: "ஃபதேபூர்", telugu: "ఫతేపూర్", marathi: "फतेहपूर" },
        { english: "Firozabad", hindi: "फिरोजाबाद", tamil: "ஃபிரோசாபாத்", telugu: "ఫిరోజాబాద్", marathi: "फिरोजाबाद" },
        { english: "Gajraula", hindi: "गजरौला", tamil: "கஜ்ரௌலா", telugu: "గజ్రౌలా", marathi: "गजरौला" },
        { english: "Gautam Buddha Nagar", hindi: "गौतमबुद्धनगर", tamil: "கௌதம் புத்த நகர்", telugu: "గౌతమ్ బుద్ధ నగర్", marathi: "गौतम बुद्ध नगर" },
        { english: "Ghaziabad", hindi: "गाज़ियाबाद", tamil: "காசியாபாத்", telugu: "ఘజియాబాద్", marathi: "गाझियाबाद" },
        { english: "Ghazipur", hindi: "गाजीपुर", tamil: "காஜிபூர்", telugu: "ఘాజీపూర్", marathi: "गाझीपूर" },
        { english: "Gonda", hindi: "गोंडा", tamil: "கோண்டா", telugu: "గోండా", marathi: "गोंडा" },
        { english: "Gorakhpur", hindi: "गोरखपुर", tamil: "கோரக்பூர்", telugu: "గోరఖ్‌పూర్", marathi: "गोरखपूर" },
        { english: "Hamirpur", hindi: "हमीरपुर", tamil: "ஹமிர்பூர்", telugu: "హమీర్పూర్", marathi: "हमीरपूर" },
        { english: "Hapur", hindi: "हापुड़", tamil: "ஹாபூர்", telugu: "హాపూర్", marathi: "हापूर" },
        { english: "Hardoi", hindi: "हरदोई", tamil: "ஹர்டோய்", telugu: "హర్డోయ్", marathi: "हरदोई" },
        { english: "Hathras", hindi: "हाथरस", tamil: "ஹத்ராஸ்", telugu: "హత్రాస్", marathi: "हातरस" },
        { english: "Jalaun", hindi: "जालौन", tamil: "ஜலான்", telugu: "జలౌన్", marathi: "जालौन" },
        { english: "Jaunpur", hindi: "जौनपुर", tamil: "ஜான்பூர்", telugu: "జౌన్‌పూర్", marathi: "जौनपूर" },
        { english: "Jhansi", hindi: "झाँसी", tamil: "ஜான்சி", telugu: "ఝాన్సీ", marathi: "झाशी" },
        { english: "Jyotiba Phule Nagar", hindi: "ज्योतिबा फुले नगर", tamil: "ஜோதிபா பூலே நகர்", telugu: "జ్యోతిబా ఫూలే నగర్", marathi: "ज्योतिबा फुले नगर" },
        { english: "Kannauj", hindi: "कन्नौज", tamil: "கன்னௌஜ்", telugu: "కన్నౌజ్", marathi: "कन्नौज" },
        { english: "Kanpur Dehat", hindi: "कानपुर देहात", tamil: "கான்பூர் தேஹாத்", telugu: "కాన్పూర్ దేహత్", marathi: "कानपूर देहाट" },
        { english: "Kanpur Nagar", hindi: "कानपुर नगर", tamil: "கான்பூர் நகர்", telugu: "కాన్పూర్ నగర్", marathi: "कानपूर नगर" },
        { english: "Kanshiram Nagar", hindi: "कांशीराम नगर", tamil: "கன்ஷிராம் நகர்", telugu: "కాన్షీరామ్ నగర్", marathi: "कांशीराम नगर" },
        { english: "Kasganj", hindi: "कासगंज", tamil: "கஸ்கஞ்ச்", telugu: "కస్గంజ్", marathi: "कासगंज" },
        { english: "Kaushambi", hindi: "कौशाम्बी", tamil: "கௌசாம்பி", telugu: "కౌశాంబి", marathi: "कौशांबी" },
        { english: "Kheri", hindi: "खेरी", tamil: "கெரி", telugu: "ఖేరీ", marathi: "खेरी" },
        { english: "Kushinagar", hindi: "कुशीनगर", tamil: "குஷிநகர்", telugu: "ఖుషీనగర్", marathi: "कुशीनगर" },
        { english: "Lakhimpur Kheri", hindi: "लखीमपुर खीरी", tamil: "லக்கிம்பூர் கெரி", telugu: "లఖింపూర్ ఖేరీ", marathi: "लखीमपूर खेरी" },
        { english: "Lalitpur", hindi: "ललितपुर", tamil: "லலித்பூர்", telugu: "లలిత్పూర్", marathi: "ललितपूर" },
        { english: "Lucknow", hindi: "लखनऊ", tamil: "லக்னோ", telugu: "లక్నో", marathi: "लखनौ" },
      { english: "Mahamaya Nagar", hindi: "महामाया नगर", tamil: "மகாமாயா நகர்", telugu: "మహామాయా నగర్", marathi: "महामाया नगर" },
      { english: "Mahoba", hindi: "महोबा", tamil: "மஹோபா", telugu: "మహోబా", marathi: "महोबा" },
      { english: "Mahrajganj", hindi: "महराजगंज", tamil: "மஹராஜ்கஞ்ச்", telugu: "మహరాజ్‌గంజ్", marathi: "महराजगंज" },
      { english: "Mainpuri", hindi: "मैनपुरी", tamil: "மெயின்புரி", telugu: "మెయిన్‌పురి", marathi: "मैनपुरी" },
      { english: "Mathura", hindi: "मथुरा", tamil: "மதுரா", telugu: "మధుర", marathi: "मथुरा" },
      { english: "Mau", hindi: "मऊ", tamil: "மௌ", telugu: "మౌ", marathi: "मौ" },
      { english: "Meerut", hindi: "मेरठ", tamil: "மீரட்", telugu: "మీరట్", marathi: "मेरठ" },
      { english: "Mirzapur", hindi: "मिर्ज़ापुर", tamil: "மிர்சாபூர்", telugu: "మీర్జాపూర్", marathi: "मिर्झापूर" },
      { english: "Moradabad", hindi: "मुरादाबाद", tamil: "மொராதாபாத்", telugu: "మొరాదాబాద్", marathi: "मुरादाबाद" },
      { english: "Muzaffarnagar", hindi: "मुजफ्फरनगर", tamil: "முசாபர்நகர்", telugu: "ముజఫర్‌నగర్", marathi: "मुझफ्फरनगर" },
      { english: "Noida", hindi: "नोएडा", tamil: "நொய்டா", telugu: "నోయిడా", marathi: "सिल्वासा" },
      { english: "Pilibhit", hindi: "पीलीभीत", tamil: "பிலிபித்", telugu: "పిలిభిత్", marathi: "पिलीभीत" },
      { english: "Pratapgarh", hindi: "प्रतापगढ़", tamil: "பிரதாப்கர்", telugu: "ప్రతాప్‌గఢ్", marathi: "प्रतापगड" },
      { english: "Prayagraj", hindi: "प्रयागराज", tamil: "பிரயாக்ராஜ்", telugu: "ప్రయాగ్రాజ్", marathi: "प्रयागराज" },
      { english: "Rae Bareli", hindi: "रायबरेली", tamil: "ரேபரேலி", telugu: "రాయ్ బరేలీ", marathi: "रायबरेली" },
      { english: "Rampur", hindi: "रामपुर", tamil: "ராம்பூர்", telugu: "రాంపూర్", marathi: "रामपूर" },
      { english: "Saharanpur", hindi: "सहारनपुर", tamil: "சஹாரன்பூர்", telugu: "సహరాన్‌పూర్", marathi: "सहारनपूर" },
      { english: "Sambhal", hindi: "संभल", tamil: "சம்பல்", telugu: "సంభాల్", marathi: "संभळ" },
      { english: "Sant Kabir Nagar", hindi: "संत कबीर नगर", tamil: "சந்த் கபீர் நகர்", telugu: "సంత్ కబీర్ నగర్", marathi: "संत कबीर नगर" },
      { english: "Shahjahanpur", hindi: "शाहजहांपुर", tamil: "ஷாஜஹான்பூர்", telugu: "షాజహాన్‌పూర్", marathi: "शहाजहानपूर" },
      { english: "Shamli", hindi: "शामली", tamil: "ஷாம்லி", telugu: "షామ్లీ", marathi: "शामली" },
      { english: "Shikohabad", hindi: "शिकोहाबाद", tamil: "ஷிகோஹாபாத்", telugu: "షికోహాబాద్", marathi: "शिकोहाबाद" },
      { english: "Shravasti", hindi: "श्रावस्ती", tamil: "ஷ்ரவஸ்தி", telugu: "శ్రావస్తి", marathi: "श्रावस्ती" },
      { english: "Siddharthnagar", hindi: "सिद्धार्थनगर", tamil: "சித்தார்த்நகர்", telugu: "సిద్ధార్థనగర్", marathi: "सिद्धार्थनगर" },
      { english: "Sitapur", hindi: "सीतापुर", tamil: "சீதாபூர்", telugu: "సీతాపూర్", marathi: "सीतापूर" },
      { english: "Sonbhadra", hindi: "सोनभद्र", tamil: "சோன்பத்ரா", telugu: "సోనభద్ర", marathi: "सोनभद्र" },
      { english: "Sultanpur", hindi: "सुल्तानपुर", tamil: "சுல்தான்பூர்", telugu: "సుల్తాన్‌పూర్", marathi: "सुलतानपूर" },
      { english: "Unnao", hindi: "उन्नाव", tamil: "உன்னாவ்", telugu: "ఉన్నావ్", marathi: "उन्नाव" },
      { english: "Varanasi", hindi: "वाराणसी", tamil: "வாரணாசி", telugu: "వారణాసి", marathi: "वाराणसी" },
      ];
    }
  }
  
  export default UttarPradeshVsDistrictsRepo;
  