class UsedTractorBrandStateCityPriceListingPageUrls {
    static getUsedTractorBrandStateCityPriceListingPageUrls() {
        return [
 
'used-tractor-in-andaman-and-nicobar-islands/',  
'used-tractor-in-andhra-pradesh/',  
'used-tractor-in-bihar/',  
'used-tractor-in-chhattisgarh/',  
'used-tractor-in-gujarat/',  
'used-tractor-in-haryana/',  
'used-tractor-in-himachal-pradesh/',  
'used-tractor-in-jharkhand/',  
'used-tractor-in-karnataka/',  
'used-tractor-in-madhya-pradesh/',  
'used-tractor-in-maharashtra/',  
'used-tractor-in-odisha/',  
'used-tractor-in-rajasthan/',  
'used-tractor-in-telangana/',  
'used-tractor-in-uttar-pradesh/',  
'used-tractor-in-west-bengal/',  
'used-tractor/massey-ferguson/241-di-173338/189349/',  
'used-tractor/massey-ferguson/massey-ferguson-1035-di-167887/183898/',  
'used-tractor/massey-ferguson/massey-ferguson-1035-di-174272/190283/',  
'used-tractor/massey-ferguson/massey-ferguson-1035-di-maha-shakti-174374/190385/',  
'used-tractor/massey-ferguson/massey-ferguson-241-di-169932/185943/',  
'used-tractor/massey-ferguson/massey-ferguson-241-di-179005/195016/',  
'used-tractor/massey-ferguson/massey-ferguson-241-di-maha-shakti-169307/185318/',  
'used-tractor/massey-ferguson/massey-ferguson-241-di-maha-shakti-176949/192960/',  
'used-tractors-for-sell/',  
'used-tractors/2019-model/',  
'used-tractors/2020-model/',  
'used-tractors/2021-model/',  
'used-tractors/2022-model/',  
'used-tractors/2023-model/',  
'used-tractors/2024-model/',  
'used-tractors/2025-model/',  
'used-tractors/above-5-lakh/',  
'used-tractors/above-50-hp/',  
'used-tractors/ace/',  
'used-tractors/below-2018-model/',  
'used-tractors/eicher/',  
'used-tractors/farmtrac/',  
'used-tractors/indo-farm/',  
'used-tractors/john-deere/',  
'used-tractors/kubota/',  
'used-tractors/mahindra/',  
'used-tractors/massey-ferguson/',  
'used-tractors/massey-ferguson/rajasthan/',  
'used-tractors/massey-ferguson/rajasthan/ajmer/',  
'used-tractors/new-holland/',  
'used-tractors/powertrac/',  
'used-tractors/preet/',  
'used-tractors/same-deutz-fahr/',  
'used-tractors/solis/',  
'used-tractors/sonalika/',  
'used-tractors/swaraj/',  
'used-tractors/under-2-lakh/',  
'used-tractors/under-20-hp/',  
'used-tractors/under-3-lakh/',  
'used-tractors/under-30-hp/',  
'used-tractors/under-4-lakh/',  
'used-tractors/under-40-hp/',  
'used-tractors/under-45-hp/',  
'used-tractors/under-5-lakh/',  
'used-tractors/under-50-hp/',  
'used-tractors/vst-shakti/',  
  
        ];
    }
  }
  
  export default UsedTractorBrandStateCityPriceListingPageUrls;