class UsedFarmImplementsListingPageUrls {
    static getUsedFarmImplementsListingPageUrls() {
        return [
 
'sell/farm-implements/',  
'sell/harvester/',  
'used-farm-implements-for-sell/',  
'used-farm-implements-for-sell/cultivator/',  
'used-farm-implements-for-sell/harrow/',  
'used-farm-implements-for-sell/laser-land-leveler/',  
'used-farm-implements-for-sell/mud-loader/',  
'used-farm-implements-for-sell/plough/',  
'used-farm-implements-for-sell/power-tiller/',  
'used-farm-implements-for-sell/reapers/',  
'used-farm-implements-for-sell/rice-transplanter/',  
'used-farm-implements-for-sell/ripper/',  
'used-farm-implements-for-sell/rotary-tiller-rotavator/',  
'used-farm-implements-for-sell/seed-drill/',  
'used-farm-implements-for-sell/straw-reaper/',  
'used-farm-implements-for-sell/super-seeder/',  
'used-farm-implements-for-sell/thresher/',  
'used-farm-implements-for-sell/trailer/',  
'used-farm-implements-for-sell/trolley/',  
'used-farm-implements-in-andhra-pradesh/',  
'used-farm-implements-in-bihar/',  
'used-farm-implements-in-chhattisgarh/',  
'used-farm-implements-in-gujarat/',  
'used-farm-implements-in-haryana/',  
'used-farm-implements-in-jharkhand/',  
'used-farm-implements-in-karnataka/',  
'used-farm-implements-in-madhya-pradesh/',  
'used-farm-implements-in-maharashtra/',  
'used-farm-implements-in-odisha/',  
'used-farm-implements-in-punjab/',  
'used-farm-implements-in-rajasthan/',  
'used-farm-implements-in-tamil-nadu/',  
'used-farm-implements-in-telangana/',  
'used-farm-implements-in-uttar-pradesh/',  
'used-farm-implements-in-west-bengal/',  
'used-farm-implements/agristar/',  
'used-farm-implements/dashmesh/',  
'used-farm-implements/farmking/',  
'used-farm-implements/fieldking/',  
'used-farm-implements/jagatjit/',  
'used-farm-implements/john-deere/',  
'used-farm-implements/kartar/',  
'used-farm-implements/ks-group/',  
'used-farm-implements/landforce/',  
'used-farm-implements/mahindra/',  
'used-farm-implements/maschio-gaspardo/',  
'used-farm-implements/new-holland/',  
'used-farm-implements/shaktiman/',  
'used-farm-implements/sonalika/',  
'used-farm-implements/swaraj/',  
'used-farm-implements/vst-shakti/',  
'used-implement/captain/2023/5909/',  
'used-implement/dasmesh/9050610241/5903/',  
'used-implement/hamidi/misel/5898/',  
'used-implement/mahindra/2021/5904/',  
'used-implement/mahindra/2022/5914/',
'used-implement/mahindra/2022/5914/',  
'used-implement/mahindra/cutter-thresar-rajasthan/5915/',  
'used-implement/mourya/2013/5917/',  
'used-implement/shree-ram-plough/2019/5905/',  
'used-implement/shree-ram/2017/5897/',  
'used-implement/sonalika/sonalika/5916/',  
'used-implement/spectra/spl/7433/',  
'used-implement/supar-diluce/2020/5888/',  
'used-implement/super-kranti/2018/5902/',  
'used-implement/trali/2013/5901/',  
'used-implement/trali/2013/5907/',  
  
        ];
    }
  }
  
  export default UsedFarmImplementsListingPageUrls;