class UsedHarvestersListingPageUrls {
    static getUsedHarvestersListingPageUrls() {
        return [
 
'sell/farm-implements/',
'sell/harvester/',
'used-harvester-for-sell/',
'used-harvester-in-andhra-pradesh/',
'used-harvester-in-bihar/',
'used-harvester-in-chhattisgarh/',
'used-harvester-in-gujarat/',
'used-harvester-in-haryana/',
'used-harvester-in-jharkhand/',
'used-harvester-in-karnataka/',
'used-harvester-in-madhya-pradesh/',
'used-harvester-in-maharashtra/',
'used-harvester-in-odisha/',
'used-harvester-in-punjab/',
'used-harvester-in-rajasthan/',
'used-harvester-in-tamil-nadu/',
'used-harvester-in-telangana/',
'used-harvester-in-uttar-pradesh/',
'used-harvester-in-west-bengal/',
'used-harvester/claas/',
'used-harvester/dashmesh/',
'used-harvester/hind-agro/',
'used-harvester/john-deere/',
'used-harvester/john-deere/12-12-2021/5920/',
'used-harvester/john-deere/2016/5833/',
'used-harvester/john-deere/28-9-2016/5837/',
'used-harvester/john-deere/green-gold/5972/',
'used-harvester/john-deere/john-deere-5310-v5-tractor-combine-harvester/5870/',
'used-harvester/john-deere/john-deere/5895/',
'used-harvester/john-deere/w70/5857/',
'used-harvester/kartar/',
'used-harvester/kartar/4000/5818/',
'used-harvester/ks-group/',
'used-harvester/kubota/',
'used-harvester/kubota/harvest-king-dg68/5908/',
'used-harvester/kubota/kubota-dc68/5885/',
'used-harvester/mahindra/',
'used-harvester/mahindra/2017/5886/',
'used-harvester/malkit/',
'used-harvester/new-hind/',
'used-harvester/new-holland/',
'used-harvester/preet/',
'used-harvester/preet/2020-deluxe-987/5873/',
'used-harvester/preet/987/5918/',
'used-harvester/sonalika/',
'used-harvester/swaraj/',
'used-harvester/swaraj/963/5863/',
'used-harvester/swaraj/swaraj-8100-nxt/5877/',
'used-harvester/vishal/',
'used-harvester/yanmar/',
  
        ];
    }
  }
  
  export default UsedHarvestersListingPageUrls;